version: '3.8'
services:
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    container_name: gateway
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - user_management
    command: [ "./app" ]
    networks:
      - go-ms
  user_management:
    build:
      context: .
      dockerfile: services/user_management/Dockerfile
    container_name: user_management
    env_file:
      - .env.docker
    depends_on:
      - mysql
    command: ["./app"]
    networks:
      - go-ms
  mysql:
    image: mysql:8.0.32
    restart: always
    cap_add:
      - ALL
    volumes:
      - ./mysql_data/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=go-ms
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    container_name: go-ms-mysql
    networks:
      - go-ms

networks:
  go-ms:
